### ISSUE TITLE
Error processing video

### ISSUE THREAD

**Issue by michzimny** [teltek/PuMuKIT2-up2u-pr-bundle#2]
I have tried to record a short video using the instructions:
https://drive.google.com/file/d/131wdw1fL85FMdA_C-4PpKYUEmAX6cVJi/view

After embedding the video in Moodle, I get the following error message in a place, where the video should appear.

"There was an error processing the video. Please contact contact@lists.up2university.eu pointing out this video id 5b0c1dac155c2f09758b4568 and this transcoding job id 5b0c1dac155c2f09758b456b."

Could you please help me on this?

**Comment by Alfro** [comment]
Hello @michzimny, could you give it a try again? It should be working now.

**Comment by michzimny** [comment]
@Alfro, I still see the same error message.

I use staging version of Moodle at https://learn.test.up2university.eu/

**Comment by Alfro** [comment]
@michzimny Have you tried recording a new video? The previous video you tried did not upload correctly and the encoding jobs failed as a result.

**Comment by Alfro** [comment]
This should not happen with new videos being recorded on the platform, so please do report it if it happened to you again.

**Comment by michzimny** [comment]
Yes, it works now for new recordings. Thanks.
